### ISSUE TITLE
Suggestion Area

### ISSUE THREAD

**Issue by VjGamingUK** [GotNoFriends/ShadowEraCore#1]
Welcome to the "Issues" area, here you can suggest or report bugs for the plugin!

**Comment by zD12** [comment]
@VjGamingUK this is an otherwise worthless issue- I'd highly advise deleting, or otherwise removing the 'enchantment' and changing it to 'messages' then closing and locking this issue.  It isn't helpful, it isn't an actual issue, it's just spam.

**Comment by SmokeSnake** [comment]
Keep it open, its easyer to notice
