### ISSUE TITLE
NoSwear.

### ISSUE THREAD

**Issue by GotNoFriends** [GotNoFriends/ShadowEraCore#11]
To be added VERY soon

**Comment by zD12** [comment]
Why can't we allow swearing, we're swearing within our own plugin?   Shall we remove the swear words and rename "Command_fuck.java"?

**Comment by SmokeSnake** [comment]
Remove thw fucking swears

**Comment by GotNoFriends** [comment]
We will be removing /fuck

**Comment by zD12** [comment]
@GotNoFriends, we could always make it nicer...  Removing isn't necessary, but, it does need to be improved..

I've worked with a minor, tiny tiny anti-swear filter within https://github.com/GotNoFriends/ShadowEraCore/commit/0681143590ac3b750f9afb75043efa1d010e5759
