### ISSUE TITLE
Possible error with main and missing some java packages

### ISSUE THREAD

**Issue by PacksGamingHD** [GotNoFriends/ShadowEraCore#19]
Missing the me.zd12.* packages (star means whatever goes there)
and also in your plugin.yml for me it doesnt run
[01:51:15 ERROR]: Could not load 'plugins/ShadowEra.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Cannot find main class `me.BrandonSteed.ShadowEra'

**Comment by PacksGamingHD** [comment]
Uhm hello?

**Comment by GotNoFriends** [comment]
Works for me?

**Comment by theLAZYway01** [comment]
Uh, what are the dependencies to build this plugin?

**Comment by PacksGamingHD** [comment]
BukkitLib and CB. Would be useful if you had a Pom.xml

**Comment by PacksGamingHD** [comment]
I believe it's the case. I'll try when I get home

**Comment by DaPancake** [comment]
zd12's packages will be removed but credit will be given for his commands he created.

This isn't meant to exclude your credit and give us all of it, but to enable the plugin to work without errors.

When created, Removal of credit for zD12's commands is prohibited and you will be subject to DMCA takedown. This will be added to the license when some type of credit command or thing is given.

Closes #19
