### ISSUE TITLE
Copyright infringement 

### ISSUE THREAD

**Issue by zD12** [GotNoFriends/ShadowEraCore#20]
The items I've developed have since been changed, without my consent nor permission.   I'm either going to request for the reverting of those edits, if that isn't possible, I wish for ALL my modifications to be reverted as well with removal of my developer status.  @GotNoFriends, I do believe this regards you, primarily.  You didn't rename my classes, instead, you deleted my classes and posted them as you own, showing that within Github, you created them- thus, infringing upon my rights and international law.   If failure to comply with my requests, I will be forced to take legal action regarding this violation of the law.

For example, 
![a6fk5de](https://cloud.githubusercontent.com/assets/7622961/6450273/bb14353c-c0f4-11e4-9642-81037e654d6d.png)
The following source code was purely written, and tested by myself- however, due to this unjustifiably neglect and infringement upon my rights.  It shows you've written the source code purely for yourself, which, isn't true. 

![4narnbf](https://cloud.githubusercontent.com/assets/7622961/6450368/5782350e-c0f5-11e4-9a6c-24a39e777c15.png)

Infringing content:

https://github.com/GotNoFriends/ShadowEraCore/commit/254b585c3f8cad68cc6264fe6bfe8aa1cf8c90f5
https://github.com/GotNoFriends/ShadowEraCore/commit/b92fe7cc868facf9879ce71980adde345ecfe495
https://github.com/GotNoFriends/ShadowEraCore/commit/e283dfe3633575b7a5c9407946daf307a70de7c8
https://github.com/GotNoFriends/ShadowEraCore/commit/be10b95858eafdcba1c97113499924c8bd06e0eb
https://github.com/GotNoFriends/ShadowEraCore/commit/72e38202b54233781e2e1f9c500bb5fb2e4bb004
https://github.com/GotNoFriends/ShadowEraCore/commit/ab12080026777b75fb282abee11282410d662da7
https://github.com/GotNoFriends/ShadowEraCore/commit/c31e309d870a9f3e865c04cf05c3cf0a3c87cd8b

**Comment by Hockeyfan360** [comment]
Taking legal action would mean hiring a lawyer and taking him to court. I have not made contributions, but I as well wish to be removed. 

(No offense) But don't be an ass, just take it up personally and/or report it to github.

**Comment by theLAZYway01** [comment]
@GotNoFriends This is to be fixed immediately or I as well will leave the team.


Added all labels and this will be CLOSED. No more arguing and turning this into a dramafest, if it isn't corrected, this will be reopened

**Comment by theLAZYway01** [comment]
Reopened so @GotNoFriends May see it.

**Comment by GotNoFriends** [comment]
I moved it for bukkitlib

**Comment by xDestroyer217** [comment]
I believe that is a lie. Pepole don't just remove massive hard-worked code for no shitty reason.

**Comment by GotNoFriends** [comment]
I added it back the commands in my package

**Comment by GotNoFriends** [comment]
I don't know why I removed strings etc

**Comment by GotNoFriends** [comment]
They are also back

**Comment by xDestroyer217** [comment]
Are you sure you actually 'put it back'

**Comment by GotNoFriends** [comment]
@zD12 you can move back the strings n all that but for the bukkit lib please leave the commands in my package :-)

**Comment by xDestroyer217** [comment]
Because, I don't see any commits of this.

**Comment by GotNoFriends** [comment]
Check my package for commands

**Comment by GotNoFriends** [comment]
Kpvp associated and the other one are in there

**Comment by GotNoFriends** [comment]
They are his commands

**Comment by GotNoFriends** [comment]
I've moved the strings and messages to main package

**Comment by xDestroyer217** [comment]
Unless cow closes this, I shall be in this.

**Comment by GotNoFriends** [comment]
Wait I forgot to readd mcstats and shelp

**Comment by GotNoFriends** [comment]
They are just in my packages to make bukkitlib work

**Comment by xDestroyer217** [comment]
No, screw it, please, just no, Cow and Hockey want to leave you anyhow. Just sayin'.

**Comment by GotNoFriends** [comment]
Hockey left.

**Comment by xDestroyer217** [comment]
Close this issue, we dont want to be in this anymore. @zD12 wants to leave.

**Comment by GotNoFriends** [comment]
Ok

**Comment by GotNoFriends** [comment]
I've removed him from repo

**Comment by PacksGamingHD** [comment]
This is unorganized...
