### ISSUE TITLE
Copyright Infringement

### ISSUE THREAD

**Issue by JeromSar** [GotNoFriends/ShadowEraCore#5]
Hey,
I've noticed that the file _Command_csay.java_ is a (near) direct copy of [Command_csay.java](https://github.com/TotalFreedom/TotalFreedomMod/blob/master/src/me/StevenLawson/TotalFreedomMod/Commands/Command_csay.java) in TFM. This file should thus be licensed under TFGL available [here](https://github.com/TotalFreedom/License). To comply to this license, please either:

a) Remove the copyrighted material from this repository; or
b) Explicitly state that this file is licensed under TFGL.

The last could be accomplished by a comment at the top of the file stating the appropriate license.

Thanks for your cooperation,
Jerom

**Comment by GotNoFriends** [comment]
Where by did we copyright it?

**Comment by SmokeSnake** [comment]
Yeah

**Comment by JeromSar** [comment]
@GotNoFriends @SmokeSnake The material in question is copyrighted by Steven Lawson and myself. It is made available in your repository without proper licensing, also known as Copyright Infringement. You may redistribute said material under the licence TFM is distributed under (TFGL). To comply with this license, you must ensure that the material remains licensed under TFGL. See my original post for instructions on how to do this.

**Comment by theLAZYway01** [comment]
@JeromSar We want our own license, this command will be redone and licensed under our consent.


Closed, Sorry for the misunderstanding

**Comment by SmokeSnake** [comment]
Reopened for Jerome's imput..

**Comment by theLAZYway01** [comment]
Jerom has no further input on this, he gave us the rules we must follow, and he is busier with other things.
