### ISSUE TITLE
Lacks proper LICENSE

### ISSUE THREAD

**Issue by zD12** [GotNoFriends/ShadowEraCore#7]
I'd suggest writing your own custom license, similar to the [following](https://github.com/TotalFreedom/License/blob/master/LICENSE.md), however..

I'd highly suggest the GNU GPL v3 or v2  modified with the EULA.

--

GNU GPL v3:

Required:

*Disclose Source
*License and copyright notice
*State Changes

Permitted:

*Commercial Use
*Distribution
*Modification
*Patent Grant
*Private Use

Forbidden:

*Hold Liable
*Sublicensing

--

The difference between v2 and v3 is slight modifications regarding what users can and cannot do.  According to [ChooseALicense](http://choosealicense.com/), "V3 is similar to V2, but further restricts use in hardware that forbids software alterations".   I'd suggest v3 generally due to the normality of GPL v3 with Mojang, Minecraft and BukkitAPI.

**Comment by zD12** [comment]
@GotNoFriends your commit has nothing to related with a license..  Reopening.

**Comment by theLAZYway01** [comment]
Adding label To Be Done


This is The responsibility of @GotNoFriends & @SmokeSnake
